
fqsuffix: "fastq.gz"
fqext1: "R1"
fqext2: "R2"

paired: True
length: 150

outdir: "G2020-87_RNA-Seq"
workdir: "/home/deepak.poduval/Snakemake-RNA-Seq"

fq_dir: "G2020-87"
ref: "/home/deepak.poduval/Ref/hg19.fa"
gtf: "/home/deepak.poduval/Ref/hg19.gtf"

### Do you have library prep tech reps- these will be merged together
## sample names must be different
# how to handle replicates
technical_replicates: merge ## change to keep to not combine
sample_sheet: "G2020-87_samples.txt"
comparisons_sheet: "G2020-87_comparisons.txt"

annotation:
  species: "hsapiens"
  ids: "SYMBOL" 


trimmomatic-pe:
  adapters: /home/deepak.poduval/miniconda3/envs/RNA-Seq.2020.12/share/trimmomatic-0.39-1/adapters/TruSeq3-SE.fa
  other: "MINLEN:10"

trimmomatic-se:
  adapters: /home/deepak.poduval/miniconda3/envs/RNA-Seq.2020.12/share/trimmomatic-0.39-1/adapters/TruSeq3-SE.fa
  other: "MINLEN:10"

# cutadapt-pe:
#   r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
#   r2_adapter: "AGATCGGAAGAGCACACGT"
#   params: "-q 0 -m 20"

# cutadapt-se:
#   r1_adapter: "AGAGCACACGTCTGAACTCCAGTCAC"
#   params: "-q 0 -m 20"  

#RNA solo ovation
#  params: "--clip_R1 5"

aligner: 'STAR'
## choose between hisat2 or STAR

star_mapping:
  params:

hisat2_mapping:
  other:
  index: "/lower_bay/local_storage/annotation_db/Mus_Musculus/UCSC/mm10/Sequence/newHisat/genome" 
  strand: "unstranded"
  ## other options: R RF

cuffnorm:
  lib: 'fr-unstranded'

use_cuffnorm_fpkms: TRUE
DESeq2:
  fdr: 0.05

pca:
  col:
    - condition
  labels: TRUE
  label_size: 2  

sample_clustering:
  row_labels: condition
  col_labels: descriptive_name

enrichment_plots:
    width: 12
    heigth: 11
    units: "in"  
## choices  
## "fr-unstranded"
## "fr-secondstrand",
## "fr-firststrand"]
featureCounts:
  other: "-p" ## paired
  strand: 0 

## choices:
## "0"
## "1"
## "2"

resources:
  trimmomatic-pe:
      mem: 300G
      time: "5:00:00"
      cpus: 16
  trimmomatic-se:
      mem: 300G
      time: "2:00:00"
      cpus: 16    
  star:
      mem: 300G
      time: "6:00:00"
      cpus: 16
  hisat:
      mem: 300G
      time: "2:00:00"
      cpus: 16      
  featureCounts:
      mem: 200G
      time: "2:00:00"
      cpus: 16   
  cuffnorm:
      mem: 200G
      time: "12:00:00"
      cpus: 16  
  bamCov:
      mem: 200G
      time: "2:00:00"
      cpus: 16 
  samtools:
      mem: 200G
      time: "1:00:00" 
      cpus: 16
  DESeq2:
      mem: 50G
      time: "30:00"
      cpus: 16        
  Enrich:
      mem: 50G
      time: "30:00"
      cpus: 16          